/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tangye_android_iso8583_POSNative */

#ifndef _Included_com_tangye_android_iso8583_POSNative
#define _Included_com_tangye_android_iso8583_POSNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tangye_android_iso8583_POSNative
 * Method:    getNativeK
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tangye_android_iso8583_POSNative_getNativeK
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
